### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by nichtich** [markusstocker/bim-108-01#1]
Open Educational Ressource?

**Comment by markusstocker** [comment]
Hallo, ja eine license soll da wohl rein ich habe von diesem Thema allerdings herzlich wenig Ahnung. Was ist der Vorteil von OER gegenüber, z.B. CC-BY?

**Comment by nichtich** [comment]
Sorry ich  meinte der Inhalt sollte eine [Open Educational Ressource](https://de.wikipedia.org/wiki/Open_Educational_Resources) sein, dafür ist eine freie Lizenz wie CC-BY notwendig. Meine Suche nach OER zu deutschsprachigen Lehrveranstaltungen aus dem Bibliotheks- und Informationsbereich war übrigens vor einigen Jahren wenig ergiebig. Auf GitHub und auch an der HsH Hannover:

* https://github.com/hshdb/MWM-317-02 (Masterstudiengang)
* https://github.com/hshdb/BIM-205-SS2017 (Projektseminar)
* https://github.com/felixlohmeier/kurs-bibliotheks-und-archivinformatik
* https://github.com/felixlohmeier/seminar-praxis-der-digitalen-bibliothek

GitHub ist auch nicht der Weisheit letzter Schluss aber noch immer besser als PDF ohne Quellen in irgendwelchen internen Lerhrmanagement-Systemen zu verstecken. P.S: Ping @felixlohmeier

**Comment by markusstocker** [comment]
Hab mir die Links angeschaut, vielen Dank. Schema.org annotierte Unterlagen haben mich beeindrückt, da geben sich Leute echt mühe! Vielleicht komme ich dann auch noch mal dazu. In der Zwischenzeit habe ich mal eine Lizenz rangehängt. Das ist schon wichtig. Vielen Dank nochmals für den Hinweis.
